
const Map<String, String> en = {
  "delete_your_account": "DELETE YOUR ACCOUNT?",
  "delete_it": "Delete",
  "cancel": "Cancel",
  "your_choice": "Your choice",
  "canceled": "Canceled",
  "to_warn": "A deleted account cannot be recovered",
  "delete_it_anyway": "Delete it anyway",
  "done_successfully": "Done successfully",
  "error": "An unexpected error occurred",
  "exit_account": "DO YOU WANT TO EXIT YOUR ACCOUNT?",
  "exit": "Exit",
  "not_available": "Section that does not exist!!!",
  "show_email": "Show email",
  "show_password": "Show password",
  "logout": "Logout",
  "delete_account": "Delete account",
  "back": "Back",
  "send_password_to_email": "Your password has been sent to your email",
  "remove_password": "REMOVE PASSWORD?",
  "no_password_set": "No password set",
  "data_not_received": "Data not received",
  "install_password": "Install password",
  "must_be_4_digits": "Must be 4 digits",
  "password": "Password",
  "confirmation_password": "Confirmation password",
  "change_password": "Change password",
  "current_password": "Current password",
  "new_password": "New password",
  "confirmation_new_password": "Confirmation new password",
  "enable_password": "Enable password",
  "disable_password": "Disable password",
  "delete_password": "Parolni o'chirish",
  "language": "Language",
  "settings": "Settings",
  "chat_bot": "Chat Bot",
  "you": "You",
  "home_page": "Home Page",
  "profile": "Profile",
  "admin": "ADMIN",
  "enter_password": "ENTER PASSWORD",
  "password_is_incorrect": "PASSWORD IS INCORRECT",
};