
const Map<String, String> ko = {
  "delete_your_account": "계정을 삭제하시겠습니까?",
  "delete_it": "삭제",
  "cancel": "취소",
  "your_choice": "당신의 선택",
  "canceled": "취소 된",
  "to_warn": "삭제된 계정은 복구할 수 없습니다",
  "delete_it_anyway": "그래도 삭제하세요",
  "done_successfully": "성공적으로 완료됨",
  "error": "예상치 못한 오류가 발생했습니다.",
  "exit_account": "계정을 종료하시겠습니까?",
  "exit": "출구",
  "not_available": "존재하지 않는 섹션!!!",
  "show_email": "이메일 표시",
  "show_password": "비밀번호 표시",
  "logout": "로그 아웃",
  "delete_account": "계정 삭제",
  "back": "뒤쪽에",
  "send_password_to_email": "귀하의 비밀번호가 귀하의 이메일로 전송되었습니다",
  "remove_password": "비밀번호를 삭제하시겠습니까?",
  "no_password_set": "비밀번호가 설정되지 않았습니다.",
  "data_not_received": "데이터가 수신되지 않았습니다",
  "install_password": "비밀번호 설치",
  "must_be_4_digits": "4자리 숫자여야 합니다.",
  "password": "비밀번호",
  "confirmation_password": "비밀번호 확인",
  "change_password": "비밀번호 변경",
  "current_password": "현재 비밀번호",
  "new_password": "새 비밀번호",
  "confirmation_new_password": "새 비밀번호 확인",
  "enable_password": "비밀번호 활성화",
  "disable_password": "비밀번호 비활성화",
  "delete_password": "파롤니 오키리쉬",
  "language": "언어",
  "settings": "설정",
  "chat_bot": "채팅봇",
  "you": "너",
  "home_page": "홈 페이지",
  "profile": "프로필",
  "admin": "관리자",
  "enter_password": "암호를 입력",
  "password_is_incorrect": "비밀번호가 맞지 않습니다",
};