
const Map<String, String> ru={
  "delete_your_account": "УДАЛИТЬ СВОЙ АККАУНТ?",
  "delete_it": "Удалить",
  "cancel": "Отмена",
  "your_choice": "Твой выбор",
  "canceled": "Отменено",
  "to_warn": "Удаленный аккаунт невозможно восстановить",
  "delete_it_anyway": "Удали его в любом случае",
  "done_successfully": "Выполнено успешно",
  "error": "произошла непредвиденная ошибка",
  "exit_account": "ВЫ ХОТИТЕ ВЫХОДИТЬ С ВАШЕГО АККАУНТА?",
  "exit": "Выход",
  "not_available": "Раздел которого не существует!!!",
  "show_email": "Показать адрес электронной почты",
  "show_password": "Показать пароль",
  "logout": "Выйти",
  "delete_account": "Удалить аккаунт",
  "back": "Назад",
  "send_password_to_email": "Ваш пароль был отправлен на вашу электронную почту",
  "remove_password": "УДАЛИТЬ ПАРОЛЬ?",
  "no_password_set": "Пароль не установлен",
  "data_not_received": "Данные не получены",
  "install_password": "Установить пароль",
  "must_be_4_digits": "Должно быть 4 цифры",
  "password": "Пароль",
  "confirmation_password": "Пароль подтверждения",
  "change_password": "Изменить пароль",
  "current_password": "Текущий пароль",
  "new_password": "Новый пароль",
  "confirmation_new_password": "Подтверждение нового пароля",
  "enable_password": "Включить пароль",
  "disable_password": "Отключить пароль",
  "delete_password": "Парольни о'чириш",
  "language": "Язык",
  "settings": "Настройки",
  "chat_bot": "Чат-бот",
  "you": "Ты",
  "home_page": "Домашняя страница",
  "profile": "Профиль",
  "admin": "АДМИН",
  "enter_password": "ВВЕДИТЕ ПАРОЛЬ",
  "password_is_incorrect": "НЕВЕРНЫЙ ПАРОЛЬ",
};