
const Map<String, String> tr = {
  "delete_your_account": "HESABINI SİL?",
  "delete_it": "Silmek",
  "cancel": "İptal etmek",
  "your_choice": "Senin seçimin",
  "canceled": "İptal edildi",
  "to_warn": "Silinen hesap kurtarılamaz",
  "delete_it_anyway": "Yine de sil",
  "done_successfully": "Başarıyla yapıldı",
  "error": "Beklenmedik bir hata oluştu",
  "exit_account": "HESABINIZDAN ÇIKMAK MI İSTİYORSUNUZ?",
  "exit": "çıkış",
  "not_available": "Bulunmayan bölüm!!!",
  "show_email": "E-postayı göster",
  "show_password": "Şifreyi göster",
  "logout": "Çıkış Yap",
  "delete_account": "Hesabı sil",
  "back": "Geri",
  "send_password_to_email": "Şifreniz e-posta adresinize gönderildi",
  "remove_password": "ŞİFREYİ KALDIR?",
  "no_password_set": "Şifre ayarlanmadı",
  "data_not_received": "Veri alınmadı",
  "install_password": "Şifreyi yükle",
  "must_be_4_digits": "4 haneli olmalı",
  "password": "Şifre",
  "confirmation_password": "Onay şifresi",
  "change_password": "Şifre değiştir",
  "current_password": "Mevcut Şifre",
  "new_password": "Yeni Şifre",
  "confirmation_new_password": "Yeni şifrenin onaylanması",
  "enable_password": "Şifreyi etkinleştir",
  "disable_password": "Şifreyi devre dışı bırak",
  "delete_password": "Parolni o'chirish",
  "language": "Dil",
  "settings": "Ayarlar",
  "chat_bot": "Sohbet Botu",
  "you": "Sen",
  "home_page": "Ana Sayfa",
  "profile": "Profil",
  "admin": "YÖNETİCİ",
  "enter_password": "PAROLANI GİR",
  "password_is_incorrect": "ŞİFRE YANLIŞ",
};