
const Map<String, String> uz = {
  "delete_your_account": "ACCOUNTINGIZ O'CHIRILSINMI ?",
  "delete_it": "O'chirilsin",
  "cancel": "Bekor qilish",
  "your_choice": "Sizning tanlovingiz",
  "canceled": "Bekor qilindi",
  "to_warn": "O'chirilgan hisobni qayta tiklab bolmaydi",
  "delete_it_anyway": "Baribir o'chirilsin",
  "done_successfully": "Muvofaqiyatli bajarildi",
  "error": "Kutilmagan xatolik yuz berdi",
  "exit_account": "ACCOUNTDAN CHIQMOQCHIMISIZ ?",
  "exit": "Chiqish",
  "not_available": "Mavjud bo'lmagan bo'lim!!!",
  "show_email": "Emailni ko'rish",
  "show_password": "Parolni ko'rish",
  "logout": "Accountdan chiqish",
  "delete_account": "Accountni o'chirish",
  "back": "Orqaga",
  "send_password_to_email": "Parolingiz emailga yuborildi",
  "remove_password": "PAROLNI O'CHIRASIZMI?",
  "no_password_set": "Parol o'rnatilmagan",
  "data_not_received": "Malumotlar qabul qilinmadi",
  "install_password": "Parol o'rnatish",
  "must_be_4_digits": "4 ta raqam bo'lishi kerak",
  "password": "Parol",
  "confirmation_password": "Parolni tasdiqlash",
  "change_password": "Parolni o'zgartirish",
  "current_password": "Hozirgi parol",
  "new_password": "Yangi parol",
  "confirmation_new_password": "Yangi parolni tasdiqlash",
  "enable_password": "Parolni yoqish",
  "disable_password": "Parolni faolsilantirish",
  "delete_password": "Parolni o'chirish",
  "language": "Til",
  "settings": "Sozlamalar",
  "chat_bot": "Chat Bot",
  "you": "Siz",
  "home_page": "Bosh sahifa",
  "profile": "Profil",
  "admin": "ADMIN",
  "enter_password": "PAROLNI KIRITING",
  "password_is_incorrect": "PAROL NOTO'G'RI",
};